package com.binli.agiledev.dao.model;

import java.util.Date;

public class TCoreTable {

	private Integer tabId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_core_table.tab_name
	 *
	 * @mbggenerated Wed Apr 05 22:08:57 CST 2017
	 */
	private String tabName;
	private String charset;
	private String tabType;

	public String getCharset() {
		return charset;
	}

	public void setCharset(String charset) {
		this.charset = charset;
	}

	public String getTabType() {
		return tabType;
	}

	public void setTabType(String tabType) {
		this.tabType = tabType;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_core_table.db_id
	 *
	 * @mbggenerated Wed Apr 05 22:08:57 CST 2017
	 */
	private Integer dbId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_core_table.comment
	 *
	 * @mbggenerated Wed Apr 05 22:08:57 CST 2017
	 */
	private String comment;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_core_table.cre_tim
	 *
	 * @mbggenerated Wed Apr 05 22:08:57 CST 2017
	 */
	private Date creTim;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_core_table.tab_id
	 *
	 * @return the value of t_core_table.tab_id
	 *
	 * @mbggenerated Wed Apr 05 22:08:57 CST 2017
	 */
	public Integer getTabId() {
		return tabId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_core_table.tab_id
	 *
	 * @param tabId
	 *            the value for t_core_table.tab_id
	 *
	 * @mbggenerated Wed Apr 05 22:08:57 CST 2017
	 */
	public void setTabId(Integer tabId) {
		this.tabId = tabId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_core_table.tab_name
	 *
	 * @return the value of t_core_table.tab_name
	 *
	 * @mbggenerated Wed Apr 05 22:08:57 CST 2017
	 */
	public String getTabName() {
		return tabName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_core_table.tab_name
	 *
	 * @param tabName
	 *            the value for t_core_table.tab_name
	 *
	 * @mbggenerated Wed Apr 05 22:08:57 CST 2017
	 */
	public void setTabName(String tabName) {
		this.tabName = tabName == null ? null : tabName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_core_table.db_id
	 *
	 * @return the value of t_core_table.db_id
	 *
	 * @mbggenerated Wed Apr 05 22:08:57 CST 2017
	 */
	public Integer getDbId() {
		return dbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_core_table.db_id
	 *
	 * @param dbId
	 *            the value for t_core_table.db_id
	 *
	 * @mbggenerated Wed Apr 05 22:08:57 CST 2017
	 */
	public void setDbId(Integer dbId) {
		this.dbId = dbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_core_table.comment
	 *
	 * @return the value of t_core_table.comment
	 *
	 * @mbggenerated Wed Apr 05 22:08:57 CST 2017
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_core_table.comment
	 *
	 * @param comment
	 *            the value for t_core_table.comment
	 *
	 * @mbggenerated Wed Apr 05 22:08:57 CST 2017
	 */
	public void setComment(String comment) {
		this.comment = comment == null ? null : comment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_core_table.cre_tim
	 *
	 * @return the value of t_core_table.cre_tim
	 *
	 * @mbggenerated Wed Apr 05 22:08:57 CST 2017
	 */
	public Date getCreTim() {
		return creTim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_core_table.cre_tim
	 *
	 * @param creTim
	 *            the value for t_core_table.cre_tim
	 *
	 * @mbggenerated Wed Apr 05 22:08:57 CST 2017
	 */
	public void setCreTim(Date creTim) {
		this.creTim = creTim;
	}
}