package com.binli.agiledev.dao.model;

public class TCoreDb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_db.Id
     *
     * @mbggenerated Fri Apr 14 21:33:24 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_db.name
     *
     * @mbggenerated Fri Apr 14 21:33:24 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_db.index_sort
     *
     * @mbggenerated Fri Apr 14 21:33:24 CST 2017
     */
    private Integer indexSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_db.comment
     *
     * @mbggenerated Fri Apr 14 21:33:24 CST 2017
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_db.Id
     *
     * @return the value of t_core_db.Id
     *
     * @mbggenerated Fri Apr 14 21:33:24 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_db.Id
     *
     * @param id the value for t_core_db.Id
     *
     * @mbggenerated Fri Apr 14 21:33:24 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_db.name
     *
     * @return the value of t_core_db.name
     *
     * @mbggenerated Fri Apr 14 21:33:24 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_db.name
     *
     * @param name the value for t_core_db.name
     *
     * @mbggenerated Fri Apr 14 21:33:24 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_db.index_sort
     *
     * @return the value of t_core_db.index_sort
     *
     * @mbggenerated Fri Apr 14 21:33:24 CST 2017
     */
    public Integer getIndexSort() {
        return indexSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_db.index_sort
     *
     * @param indexSort the value for t_core_db.index_sort
     *
     * @mbggenerated Fri Apr 14 21:33:24 CST 2017
     */
    public void setIndexSort(Integer indexSort) {
        this.indexSort = indexSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_db.comment
     *
     * @return the value of t_core_db.comment
     *
     * @mbggenerated Fri Apr 14 21:33:24 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_db.comment
     *
     * @param comment the value for t_core_db.comment
     *
     * @mbggenerated Fri Apr 14 21:33:24 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}