package com.binli.agiledev.dao.model;

import java.util.Date;

public class TCoreColumn {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_core_column.col_id
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	private Integer colId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_core_column.col_name
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	private String colName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_core_column.col_type
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	private String colType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_core_column.col_index
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	private Integer colIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_core_column.col_default
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	private String colDefault;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_core_column.col_null
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	private Boolean colNull;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_core_column.tab_id
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	private Integer tabId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_core_column.comment
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	private String comment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_core_column.cre_tim
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	private Date creTim;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_core_column.col_id
	 * @return  the value of t_core_column.col_id
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public Integer getColId() {
		return colId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_core_column.col_id
	 * @param colId  the value for t_core_column.col_id
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public void setColId(Integer colId) {
		this.colId = colId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_core_column.col_name
	 * @return  the value of t_core_column.col_name
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public String getColName() {
		return colName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_core_column.col_name
	 * @param colName  the value for t_core_column.col_name
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public void setColName(String colName) {
		this.colName = colName == null ? null : colName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_core_column.col_type
	 * @return  the value of t_core_column.col_type
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public String getColType() {
		return colType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_core_column.col_type
	 * @param colType  the value for t_core_column.col_type
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public void setColType(String colType) {
		this.colType = colType == null ? null : colType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_core_column.col_index
	 * @return  the value of t_core_column.col_index
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public Integer getColIndex() {
		return colIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_core_column.col_index
	 * @param colIndex  the value for t_core_column.col_index
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public void setColIndex(Integer colIndex) {
		this.colIndex = colIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_core_column.col_default
	 * @return  the value of t_core_column.col_default
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public String getColDefault() {
		return colDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_core_column.col_default
	 * @param colDefault  the value for t_core_column.col_default
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public void setColDefault(String colDefault) {
		this.colDefault = colDefault == null ? null : colDefault.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_core_column.col_null
	 * @return  the value of t_core_column.col_null
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public Boolean getColNull() {
		return colNull;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_core_column.col_null
	 * @param colNull  the value for t_core_column.col_null
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public void setColNull(Boolean colNull) {
		this.colNull = colNull;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_core_column.tab_id
	 * @return  the value of t_core_column.tab_id
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public Integer getTabId() {
		return tabId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_core_column.tab_id
	 * @param tabId  the value for t_core_column.tab_id
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public void setTabId(Integer tabId) {
		this.tabId = tabId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_core_column.comment
	 * @return  the value of t_core_column.comment
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_core_column.comment
	 * @param comment  the value for t_core_column.comment
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public void setComment(String comment) {
		this.comment = comment == null ? null : comment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_core_column.cre_tim
	 * @return  the value of t_core_column.cre_tim
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public Date getCreTim() {
		return creTim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_core_column.cre_tim
	 * @param creTim  the value for t_core_column.cre_tim
	 * @mbggenerated  Thu Apr 06 20:55:50 CST 2017
	 */
	public void setCreTim(Date creTim) {
		this.creTim = creTim;
	}
}