package com.binli.agiledev.dao.model;

import com.binli.agiledev.model.vo.VProDbTabTreeExt;

public class VProDbTabTree extends VProDbTabTreeExt{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_pro_db_tab_tree.id
     *
     * @mbggenerated Sun Jun 04 18:51:05 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_pro_db_tab_tree.name
     *
     * @mbggenerated Sun Jun 04 18:51:05 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_pro_db_tab_tree.obj_type
     *
     * @mbggenerated Sun Jun 04 18:51:05 CST 2017
     */
    private String objType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_pro_db_tab_tree.pid
     *
     * @mbggenerated Sun Jun 04 18:51:05 CST 2017
     */
    private String pid;
    private String comment;

    
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_pro_db_tab_tree.id
     *
     * @param id the value for v_pro_db_tab_tree.id
     *
     * @mbggenerated Sun Jun 04 18:51:05 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_pro_db_tab_tree.name
     *
     * @return the value of v_pro_db_tab_tree.name
     *
     * @mbggenerated Sun Jun 04 18:51:05 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_pro_db_tab_tree.name
     *
     * @param name the value for v_pro_db_tab_tree.name
     *
     * @mbggenerated Sun Jun 04 18:51:05 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_pro_db_tab_tree.obj_type
     *
     * @return the value of v_pro_db_tab_tree.obj_type
     *
     * @mbggenerated Sun Jun 04 18:51:05 CST 2017
     */
    public String getObjType() {
        return objType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_pro_db_tab_tree.obj_type
     *
     * @param objType the value for v_pro_db_tab_tree.obj_type
     *
     * @mbggenerated Sun Jun 04 18:51:05 CST 2017
     */
    public void setObjType(String objType) {
        this.objType = objType == null ? null : objType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_pro_db_tab_tree.pid
     *
     * @return the value of v_pro_db_tab_tree.pid
     *
     * @mbggenerated Sun Jun 04 18:51:05 CST 2017
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_pro_db_tab_tree.pid
     *
     * @param pid the value for v_pro_db_tab_tree.pid
     *
     * @mbggenerated Sun Jun 04 18:51:05 CST 2017
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}
}