package com.binli.agiledev.dao.mapper;


import com.binli.agiledev.dao.model.TCoreColumn;
import com.binli.agiledev.dao.model.TCoreDb;

public interface TCoreDBMapper {
     
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_core_db
	 * @mbggenerated  Wed Apr 12 21:08:29 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_core_db
	 * @mbggenerated  Wed Apr 12 21:08:29 CST 2017
	 */
	int insert(TCoreDb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_core_db
	 * @mbggenerated  Wed Apr 12 21:08:29 CST 2017
	 */
	int insertSelective(TCoreDb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_core_db
	 * @mbggenerated  Wed Apr 12 21:08:29 CST 2017
	 */
	TCoreDb selectByPrimaryKey(Integer id);

	
	int updateByPrimaryKeySelective(TCoreDb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_core_db
	 * @mbggenerated  Wed Apr 12 21:08:29 CST 2017
	 */
	int updateByPrimaryKey(TCoreDb record);

	 
 
}