package com.binli.agiledev.dao.mapper;

import com.binli.agiledev.dao.model.TCoreTable;

public interface TCoreTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_table
     *
     * @mbggenerated Wed Apr 05 22:08:57 CST 2017
     */
    int deleteByPrimaryKey(Integer tabId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_table
     *
     * @mbggenerated Wed Apr 05 22:08:57 CST 2017
     */
    int insert(TCoreTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_table
     *
     * @mbggenerated Wed Apr 05 22:08:57 CST 2017
     */
    int insertSelective(TCoreTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_table
     *
     * @mbggenerated Wed Apr 05 22:08:57 CST 2017
     */
    TCoreTable selectByPrimaryKey(Integer tabId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_table
     *
     * @mbggenerated Wed Apr 05 22:08:57 CST 2017
     */
    int updateByPrimaryKeySelective(TCoreTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_table
     *
     * @mbggenerated Wed Apr 05 22:08:57 CST 2017
     */
    int updateByPrimaryKey(TCoreTable record);
}