package com.binli.agiledev.dao.mapper;

import java.util.List;

import com.binli.agiledev.dao.model.TCoreColumn;

public interface TCoreColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_column
     *
     * @mbggenerated Wed Apr 05 21:54:29 CST 2017
     */
    int deleteByPrimaryKey(Integer colId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_column
     *
     * @mbggenerated Wed Apr 05 21:54:29 CST 2017
     */
    int insert(TCoreColumn record);
     int insertByBatch(List<TCoreColumn> record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_column
     *
     * @mbggenerated Wed Apr 05 21:54:29 CST 2017
     */
    int insertSelective(TCoreColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_column
     *
     * @mbggenerated Wed Apr 05 21:54:29 CST 2017
     */
    TCoreColumn selectByPrimaryKey(Integer colId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_column
     *
     * @mbggenerated Wed Apr 05 21:54:29 CST 2017
     */
    int updateByPrimaryKeySelective(TCoreColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_column
     *
     * @mbggenerated Wed Apr 05 21:54:29 CST 2017
     */
    int updateByPrimaryKey(TCoreColumn record);
}